<?php

return [
    'units' => [
        'pondok_group' => [
            'Ponpes As-Sunnah Gorontalo',
            'MTS As-Sunnah Gorontalo',
            'MA As-Sunnah Limboto Barat',
        ],
    ],

    'roles' => [
        'admin_unit' => [
            'label' => 'Admin Unit',
            'scope' => 'unit',
            'assignable_by' => ['superadmin'],
        ],
        'kepala_madrasah' => [
            'label' => 'Kepala Madrasah',
            'scope' => 'unit',
            'assignable_by' => ['superadmin', 'admin_unit'],
        ],
        'wakamad_kurikulum' => [
            'label' => 'Wakamad Kurikulum',
            'scope' => 'unit',
            'assignable_by' => ['superadmin', 'admin_unit', 'kepala_madrasah'],
        ],
        'wakamad_kesiswaan' => [
            'label' => 'Wakamad Kesiswaan',
            'scope' => 'unit',
            'assignable_by' => ['superadmin', 'admin_unit', 'kepala_madrasah'],
        ],
        'wakamad_sarpras' => [
            'label' => 'Wakamad Sarpras',
            'scope' => 'unit',
            'assignable_by' => ['superadmin', 'admin_unit', 'kepala_madrasah'],
        ],
        'bendahara' => [
            'label' => 'Bendahara',
            'scope' => 'unit',
            'assignable_by' => ['superadmin', 'admin_unit', 'kepala_madrasah'],
        ],
        'wali_kelas' => [
            'label' => 'Wali Kelas',
            'scope' => 'unit',
            'assignable_by' => ['superadmin', 'admin_unit', 'kepala_madrasah'],
        ],
        'mudir_pondok' => [
            'label' => 'Mudir Pondok',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin'],
        ],
        'naibul_mudir' => [
            'label' => 'Naibul Mudir',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'mudir_pondok'],
        ],
        'naibatul_mudir' => [
            'label' => 'Naibatul Mudir',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'mudir_pondok'],
        ],
        'kabag_kesantrian_putra' => [
            'label' => 'Kabag Kesantrian Putra',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'mudir_pondok'],
        ],
        'kabag_kesantrian_putri' => [
            'label' => 'Kabag Kesantrian Putri',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'mudir_pondok'],
        ],
        'kabag_umum' => [
            'label' => 'Kabag Umum',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'mudir_pondok'],
        ],
        'koor_kesehatan_putra' => [
            'label' => 'Koor Kesehatan Putra',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_kesantrian_putra'],
        ],
        'koor_kesehatan_putri' => [
            'label' => 'Koor Kesehatan Putri',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_kesantrian_putri'],
        ],
        'koor_kebersihan_putra' => [
            'label' => 'Koor Kebersihan Putra',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_kesantrian_putra'],
        ],
        'koor_kebersihan_putri' => [
            'label' => 'Koor Kebersihan Putri',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_kesantrian_putri'],
        ],
        'koor_keamanan_putra' => [
            'label' => 'Koor Keamanan Putra',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_kesantrian_putra'],
        ],
        'koor_keamanan_putri' => [
            'label' => 'Koor Keamanan Putri',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_kesantrian_putri'],
        ],
        'koor_tahfizh_putra' => [
            'label' => 'Koor Tahfizh Putra',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_kesantrian_putra'],
        ],
        'koor_tahfizh_putri' => [
            'label' => 'Koor Tahfizh Putri',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_kesantrian_putri'],
        ],
        'koor_lughoh_putra' => [
            'label' => 'Koor Lughoh Putra',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_kesantrian_putra'],
        ],
        'koor_lughoh_putri' => [
            'label' => 'Koor Lughoh Putri',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_kesantrian_putri'],
        ],
        'koor_kepegawaian' => [
            'label' => 'Koor Kepegawaian',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_umum'],
        ],
        'koor_sarpras' => [
            'label' => 'Koor Sarpras',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_umum'],
        ],
        'koor_dapur' => [
            'label' => 'Koor Dapur',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_umum'],
        ],
        'koor_logistik' => [
            'label' => 'Koor Logistik',
            'scope' => 'pondok',
            'assignable_by' => ['superadmin', 'kabag_umum'],
        ],
    ],

    'panels' => [
        'pendidikan' => [
            'label' => 'Unit Pendidikan',
            'entries' => [
                [
                    'roles' => ['kepala_madrasah'],
                    'title' => 'Panel Kepala Madrasah',
                    'short_label' => 'Kepala Madrasah',
                    'description' => 'Ringkasan santri, guru, dan capaian akademik unit.',
                    'route' => 'module.kepala',
                    'pattern' => 'modul/kepala-madrasah*',
                    'icon' => '🎓',
                ],
                [
                    'roles' => ['wakamad_kurikulum'],
                    'title' => 'Panel Wakamad Kurikulum',
                    'short_label' => 'Wakamad Kurikulum',
                    'description' => 'Kelola kalender pendidikan dan penugasan mapel.',
                    'route' => 'module.wakamad.kurikulum',
                    'pattern' => 'modul/wakamad-kurikulum*',
                    'icon' => '📘',
                ],
                [
                    'roles' => ['wakamad_kesiswaan'],
                    'title' => 'Panel Wakamad Kesiswaan',
                    'short_label' => 'Wakamad Kesiswaan',
                    'description' => 'Pantau kedisiplinan, absensi, dan pelaporan wali kelas.',
                    'route' => 'module.wakamad.kesiswaan',
                    'pattern' => 'modul/wakamad-kesiswaan*',
                    'icon' => '🧑‍🤝‍🧑',
                ],
                [
                    'roles' => ['wakamad_sarpras'],
                    'title' => 'Panel Wakamad Sarpras',
                    'short_label' => 'Wakamad Sarpras',
                    'description' => 'Kelola kebutuhan sarana prasarana tiap unit.',
                    'route' => 'module.wakamad.sarpras',
                    'pattern' => 'modul/wakamad-sarpras*',
                    'icon' => '🏫',
                ],
            ],
        ],
        'nilai_mapel' => [
            'label' => 'Pengelolaan Nilai & Mapel',
            'entries' => [
                [
                    'roles' => ['wali_kelas'],
                    'title' => 'Panel Wali Kelas',
                    'short_label' => 'Wali Kelas',
                    'description' => 'Input nilai dan rilis raport santri.',
                    'route' => 'module.wali-kelas',
                    'pattern' => 'modul/wali-kelas*',
                    'icon' => '📑',
                ],
                [
                    'roles' => ['guru_mapel_umum', 'guru_mapel_syari'],
                    'title' => 'Panel Guru Mapel',
                    'short_label' => 'Guru Mapel',
                    'description' => 'Kelola nilai dan absensi mapel umum maupun syar’i.',
                    'route' => 'module.guru-mapel',
                    'pattern' => 'modul/guru-mapel*',
                    'icon' => '📚',
                ],
            ],
        ],
        'halaqoh_hafalan' => [
            'label' => 'Halaqoh & Hafalan',
            'entries' => [
                [
                    'roles' => ['guru', 'wali_kelas', 'koordinator_tahfizh_putra', 'koordinator_tahfizh_putri', 'superadmin'],
                    'title' => 'Dashboard Guru',
                    'short_label' => 'Dashboard Guru',
                    'description' => 'Pantau ringkasan halaqoh, setoran, dan santri binaan.',
                    'route' => 'guru.dashboard',
                    'pattern' => 'guru/dashboard*',
                    'icon' => '🧑‍🏫',
                ],
                [
                    'roles' => ['guru', 'wali_kelas', 'koordinator_tahfizh_putra', 'koordinator_tahfizh_putri', 'superadmin'],
                    'title' => 'Setoran Hafalan',
                    'short_label' => 'Setoran Hafalan',
                    'description' => 'Input setoran harian dan review progres hafalan.',
                    'route' => 'guru.setoran.index',
                    'pattern' => 'guru/setoran*',
                    'icon' => '🕌',
                ],
                [
                    'roles' => ['superadmin','admin','admin_unit','koordinator_tahfizh_putra','koordinator_tahfizh_putri','guru','wali_kelas'],
                    'title' => 'Dashboard Tahfizh Qur\'an',
                    'short_label' => 'Tahfizh Qur\'an',
                    'description' => 'Monitor tren setoran Qur\'an lintas unit dan halaqoh.',
                    'route' => 'program.tahfizh-quran',
                    'pattern' => 'program/tahfizh-quran*',
                    'icon' => '📖',
                ],
            ],
        ],
        'koordinasi_tahfizh' => [
            'label' => 'Koordinasi Tahfizh',
            'entries' => [
                [
                    'roles' => ['koordinator_tahfizh_putra','koordinator_tahfizh_putri','admin','superadmin'],
                    'title' => 'Kelola Halaqoh',
                    'short_label' => 'Kelola Halaqoh',
                    'description' => 'Atur pengampu, santri, dan struktur halaqoh lintas unit.',
                    'route' => 'tahfizh.halaqoh.index',
                    'pattern' => 'tahfizh/halaqoh*',
                    'icon' => '🌿',
                ],
            ],
        ],
        'laporan' => [
            'label' => 'Laporan & Monitoring',
            'entries' => [
                [
                    'roles' => ['superadmin','admin','admin_unit'],
                    'title' => 'Laporan Hafalan Qur\'an',
                    'short_label' => 'Laporan Hafalan',
                    'description' => 'Pantau rekap hafalan per santri dan unit pendidikan.',
                    'route' => 'admin.laporan.hafalan',
                    'pattern' => 'admin/laporan/hafalan*',
                    'icon' => '📊',
                ],
            ],
        ],
        'keuangan' => [
            'label' => 'Keuangan Yayasan',
            'entries' => [
                [
                    'roles' => ['bendahara'],
                    'title' => 'Panel Bendahara',
                    'short_label' => 'Bendahara',
                    'description' => 'Input administrasi dan laporan keuangan.',
                    'route' => 'module.bendahara',
                    'pattern' => 'modul/bendahara*',
                    'icon' => '💰',
                ],
            ],
        ],
        'pondok' => [
            'label' => 'Pondok Pesantren',
            'entries' => [
                [
                    'roles' => ['mudir_pondok', 'naibul_mudir', 'naibatul_mudir'],
                    'title' => 'Panel Pimpinan Pondok',
                    'short_label' => 'Pimpinan Pondok',
                    'description' => 'Monitor unit pondok, MTS, dan MA di bawah naungan.',
                    'route' => 'module.mudir',
                    'pattern' => 'modul/mudir-pondok*',
                    'icon' => '🏘️',
                ],
            ],
        ],
        'kesantrian_putra' => [
            'label' => 'Kesantrian Putra',
            'entries' => [
                [
                    'roles' => ['kabag_kesantrian_putra'],
                    'title' => 'Panel Kesantrian Putra',
                    'short_label' => 'Kesantrian Putra',
                    'description' => 'Kelola koor kesehatan, kebersihan, keamanan, tahfizh, dan lughoh putra.',
                    'route' => 'module.kesantrian.putra',
                    'pattern' => 'modul/kesantrian-putra*',
                    'icon' => '🧑‍🎓',
                ],
                [
                    'roles' => ['koor_tahfizh_putra'],
                    'title' => 'Koordinator Tahfizh Putra',
                    'short_label' => 'Koor Tahfizh Putra',
                    'description' => 'Atur halaqoh, guru pengampu, dan setoran santri putra.',
                    'route' => [
                        'name' => 'module.kesantrian.tahfizh',
                        'params' => ['segment' => 'putra'],
                    ],
                    'pattern' => 'modul/kesantrian/putra/tahfizh*',
                    'icon' => '🕌',
                ],
                [
                    'roles' => ['koor_lughoh_putra'],
                    'title' => 'Koordinator Lughoh Putra',
                    'short_label' => 'Koor Lughoh Putra',
                    'description' => 'Koordinasikan halaqoh lughoh serta perkembangan bahasa santri putra.',
                    'route' => 'tahfizh.halaqoh.index',
                    'pattern' => 'tahfizh/halaqoh*',
                    'icon' => '📜',
                ],
                [
                    'roles' => ['koor_kesehatan_putra'],
                    'title' => 'Koordinator Kesehatan Putra',
                    'short_label' => 'Koor Kesehatan Putra',
                    'description' => 'Catat layanan kesehatan dan tindak lanjut santri putra.',
                    'route' => 'module.koor-kesehatan',
                    'pattern' => 'modul/koor-kesehatan*',
                    'icon' => '🩺',
                ],
                [
                    'roles' => ['koor_kebersihan_putra'],
                    'title' => 'Koordinator Kebersihan Putra',
                    'short_label' => 'Koor Kebersihan Putra',
                    'description' => 'Monitoring kebersihan asrama, kelas, dan area putra.',
                    'route' => 'module.koor-kebersihan',
                    'pattern' => 'modul/koor-kebersihan*',
                    'icon' => '🧹',
                ],
                [
                    'roles' => ['koor_keamanan_putra'],
                    'title' => 'Koordinator Keamanan Putra',
                    'short_label' => 'Koor Keamanan Putra',
                    'description' => 'Kelola jadwal piket keamanan dan laporan insiden santri putra.',
                    'route' => 'module.koor-keamanan',
                    'pattern' => 'modul/koor-keamanan*',
                    'icon' => '🛡️',
                ],
            ],
        ],
        'kesantrian_putri' => [
            'label' => 'Kesantrian Putri',
            'entries' => [
                [
                    'roles' => ['kabag_kesantrian_putri'],
                    'title' => 'Panel Kesantrian Putri',
                    'short_label' => 'Kesantrian Putri',
                    'description' => 'Kelola koor kesehatan, kebersihan, keamanan, tahfizh, dan lughoh putri.',
                    'route' => 'module.kesantrian.putri',
                    'pattern' => 'modul/kesantrian-putri*',
                    'icon' => '👩‍🎓',
                ],
                [
                    'roles' => ['koor_tahfizh_putri'],
                    'title' => 'Koordinator Tahfizh Putri',
                    'short_label' => 'Koor Tahfizh Putri',
                    'description' => 'Atur halaqoh, guru pengampu, dan setoran santri putri.',
                    'route' => [
                        'name' => 'module.kesantrian.tahfizh',
                        'params' => ['segment' => 'putri'],
                    ],
                    'pattern' => 'modul/kesantrian/putri/tahfizh*',
                    'icon' => '🕌',
                ],
                [
                    'roles' => ['koor_lughoh_putri'],
                    'title' => 'Koordinator Lughoh Putri',
                    'short_label' => 'Koor Lughoh Putri',
                    'description' => 'Koordinasikan halaqoh lughoh serta perkembangan bahasa santri putri.',
                    'route' => 'tahfizh.halaqoh.index',
                    'pattern' => 'tahfizh/halaqoh*',
                    'icon' => '📜',
                ],
                [
                    'roles' => ['koor_kesehatan_putri'],
                    'title' => 'Koordinator Kesehatan Putri',
                    'short_label' => 'Koor Kesehatan Putri',
                    'description' => 'Catat layanan kesehatan dan tindak lanjut santri putri.',
                    'route' => 'module.koor-kesehatan',
                    'pattern' => 'modul/koor-kesehatan*',
                    'icon' => '🩺',
                ],
                [
                    'roles' => ['koor_kebersihan_putri'],
                    'title' => 'Koordinator Kebersihan Putri',
                    'short_label' => 'Koor Kebersihan Putri',
                    'description' => 'Monitoring kebersihan asrama, kelas, dan area putri.',
                    'route' => 'module.koor-kebersihan',
                    'pattern' => 'modul/koor-kebersihan*',
                    'icon' => '🧹',
                ],
                [
                    'roles' => ['koor_keamanan_putri'],
                    'title' => 'Koordinator Keamanan Putri',
                    'short_label' => 'Koor Keamanan Putri',
                    'description' => 'Kelola jadwal piket keamanan dan laporan insiden santri putri.',
                    'route' => 'module.koor-keamanan',
                    'pattern' => 'modul/koor-keamanan*',
                    'icon' => '🛡️',
                ],
            ],
        ],
        'penunjang' => [
            'label' => 'Penunjang Operasional',
            'entries' => [
                [
                    'roles' => ['kabag_umum'],
                    'title' => 'Panel Kabag Umum',
                    'short_label' => 'Kabag Umum',
                    'description' => 'Koordinasikan kepegawaian, sarpras, dapur, dan logistik.',
                    'route' => 'module.kabag-umum',
                    'pattern' => 'modul/kabag-umum*',
                    'icon' => '🛠️',
                ],
            ],
        ],
        'wali' => [
            'label' => 'Wali Santri',
            'entries' => [
                [
                    'roles' => ['wali_santri'],
                    'title' => 'Data Anak & Dashboard',
                    'short_label' => 'Dashboard Wali',
                    'description' => 'Lihat ringkasan progres anak dan informasi terbaru.',
                    'route' => 'wali.dashboard',
                    'pattern' => 'wali/dashboard*',
                    'icon' => '👨‍👩‍👧',
                ],
                [
                    'roles' => ['wali_santri'],
                    'title' => 'Progres Hafalan',
                    'short_label' => 'Progres Hafalan',
                    'description' => 'Pantau capaian hafalan, kesehatan, dan catatan wali kelas.',
                    'route' => 'wali.progres',
                    'pattern' => 'wali/progres*',
                    'icon' => '📈',
                ],
                [
                    'roles' => ['wali_santri'],
                    'title' => 'Detail Hafalan',
                    'short_label' => 'Detail Hafalan',
                    'description' => 'Lihat riwayat setoran dan evaluasi hafalan santri.',
                    'route' => 'wali.hafalan',
                    'pattern' => 'wali/hafalan*',
                    'icon' => '📖',
                ],
                [
                    'roles' => ['wali_santri'],
                    'title' => 'Profil Wali',
                    'short_label' => 'Profil Wali',
                    'description' => 'Perbarui data wali dan informasi kontak.',
                    'route' => 'wali.profil',
                    'pattern' => 'wali/profil*',
                    'icon' => '🧾',
                ],
            ],
        ],
    ],
];
